export const ActionTypes = {
 CLICK: 'click',
 CLICKVIAJS: 'CLICKVIAJS',
 DOUBLECLICK: 'doubleclick',
 SETTEXT: 'setText',
 PRESS: 'press',
 SETDROPDOWN: 'dropDown',
 SETDROPDOWNVIAVALUE: 'dropDownViaValue',
 UPLOADFILE: 'uploadFile',
 CHECK: 'check',
 UNCHECK: 'uncheck',
 VERIFY: 'verify',
 FRAMECLICK: 'frameClick',
 FRAMESET: 'frameSet',
 FRAMEVERIFY: 'frameVerify',
 HOVER: 'hover',
 SETATTRIBUTE: 'setAttribute',
 GETTEXT: 'gettext',
 RETURNELEMENT: 'getElement',
 NAVIGATETOURL: 'navigateToURl',
 HOVER_FORCE: 'hoverForce',
 CLICK_FORCED: 'clickForced',
};
export const AssertionType = {
 EQUALCHECK: 'equalcheck',
 DISPLAYED: 'displayed',
 ENABLED: 'enabled',
 DISABLED: 'disabled',
 ISSELECTED: 'isselected',
 TABLEDATAEXISTS: 'tableDataExists',
 PROPERTYCHECK: 'propertyCheck',
 NOTDISPLAYED: 'notDisplayed',
 ISHIDDEN: 'isHidden',
 VERIFYHAVECLASS: 'haveClass',
 VERIFYHAVECLASSPATTERN: 'haveClassPattern',
 VERIFYELEMENTCHECKED: 'verifyElementChecked',
 VERIFYELEMENTNOTCHECKED: 'verifyElementNotChecked',
 CONTAINTEXT: 'containText',
 ATTRIBUTENOTEXIST: 'attributeNotExist',
 NOTEXIST: 'notExist',
 CHECKED: 'checked',
 POPULATED: 'populated',
 INBETWEEN:'inBetween',
};